---
abstract: ~
author:
  - 'Toshinori Sato (@overlast) <overlasting {at} gmail.com>'
  - 'Toshinori Sato (@overlast) <overlasting {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-RankAggregate
no_index:
  directory:
    - inc
    - t
    - xt
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/overlast/p5-Algorithm-RankAggregate.git
version: 0.0.1_00
